"""Answer generation with citations."""

import re
from typing import List, Dict, Any, Optional
import numpy as np
from src.config import Config
from src.comparison.conflict_detector import ConflictDetector


class AnswerGenerator:
    """Generate answers from retrieved chunks with proper citations."""

    SECTION_MAP = {
        "introduction": ["introduction", "background", "abstract"],
        "methodology": ["method", "methods", "methodology", "approach"],
        "results": ["results", "experiments", "evaluation", "findings"],
        "discussion": ["discussion", "analysis"],
        "conclusion": ["conclusion"],
    }
    TOP_CHUNKS_PER_SECTION = 2
    MAX_SECTIONS_PER_PAPER = 3
    PARAGRAPH_MIN_SENTENCES = 3
    PARAGRAPH_MAX_SENTENCES = 5
    SUBQUERY_HARD_GATE_THRESHOLD = 0.50
    SECTION_PREFERRED_BOOST = 1.2
    CONFIDENCE_W1 = 0.45
    CONFIDENCE_W2 = 0.35
    CONFIDENCE_W3 = 0.20
    SUBQUERY_MATCH_THRESHOLD = 0.60
    SUBQUERY_STRONG_MATCH_THRESHOLD = 0.60
    FALLBACK_TOP_K_PER_SUBQ = 2
    INTENT_KEYWORDS = {
        "dataset": ["dataset", "datasets", "benchmark", "corpus", "collection", "labeled", "labeling"],
        "detection": ["detect", "detection", "identify", "mitigation", "prevent", "exploit"],
        "types": ["type", "types", "category", "taxonomy", "class", "cwe"],
        "methodology": ["method", "approach", "framework", "pipeline", "technique", "construction"],
    }
    BACKGROUND_DRIFT_TERMS = [
        "iot",
        "internet of things",
        "general overview",
        "broad introduction",
        "blockchain basics",
    ]
    DATASET_SIGNALS = [
        "dataset", "datasets", "benchmark", "corpus", "training data", "data collection", "data source"
    ]
    
    def __init__(self):
        self._last_analysis: Dict[str, Any] = {}

    def get_last_analysis(self) -> Dict[str, Any]:
        """Return structured analysis generated by the latest grouped-answer run."""
        return dict(self._last_analysis)

    # ── Phase 3: Comparison Matrix ─────────────────────────────────

    def _build_comparison_matrix(
        self,
        chunks: List[Dict[str, Any]],
        references: List[Dict[str, Any]],
    ) -> List[Dict[str, Any]]:
        """Build a per-paper comparison row from aggregated paper_facts.

        Groups all chunks by paper_id, deduplicates extracted facts, and
        creates one structured row per paper suitable for deterministic
        comparison tables and LLM prompts.

        Returns:
            Sorted list of dicts (highest avg similarity first).
        """
        from collections import Counter as _Counter

        paper_map: Dict[str, Dict[str, Any]] = {}
        ref_lookup = {r.get("paper_id", ""): r for r in (references or [])}

        for c in chunks:
            pid = str(c.get("paper_id") or "")
            if not pid:
                continue
            if pid not in paper_map:
                ref = ref_lookup.get(pid, {})
                paper_map[pid] = {
                    "paper_id": pid,
                    "title": c.get("paper_title", ref.get("title", "Unknown")),
                    "year": str(c.get("paper_year", ref.get("year", "N/A"))),
                    "doi": ref.get("doi", ""),
                    "_datasets": set(),
                    "_model_names": set(),
                    "_method_kw_counter": _Counter(),
                    "_metrics": [],
                    "_sections": set(),
                    "_best_evidence": "",
                    "_best_score": 0.0,
                    "_sim_scores": [],
                }

            row = paper_map[pid]
            facts = c.get("paper_facts") or {}
            for ds in facts.get("datasets", []):
                row["_datasets"].add(ds)
            for mn in facts.get("model_names", []):
                row["_model_names"].add(mn)
            for mk in facts.get("method_keywords", []):
                row["_method_kw_counter"][mk] += 1
            for met in facts.get("metrics", []):
                if met not in row["_metrics"]:
                    row["_metrics"].append(met)

            section = str((c.get("metadata") or {}).get("section", c.get("section", "unknown")))
            row["_sections"].add(section)

            sim = float(c.get("similarity_score", 0.0) or 0.0)
            row["_sim_scores"].append(sim)

            ev = c.get("evidence_sentence") or c.get("text", "")
            ev_score = float(c.get("evidence_score", sim) or sim)
            if ev_score > row["_best_score"]:
                row["_best_score"] = ev_score
                row["_best_evidence"] = (ev or "")[:250]

        # Flatten into clean output
        matrix: List[Dict[str, Any]] = []
        for pid, row in paper_map.items():
            avg_sim = sum(row["_sim_scores"]) / max(1, len(row["_sim_scores"]))
            top_methods = [kw for kw, _ in row["_method_kw_counter"].most_common(5)]
            matrix.append({
                "paper_id": pid,
                "title": row["title"],
                "year": row["year"],
                "doi": row["doi"],
                "datasets": sorted(row["_datasets"]),
                "model_names": sorted(row["_model_names"]),
                "method_keywords": top_methods,
                "metrics": row["_metrics"][:10],
                "sections_covered": sorted(row["_sections"]),
                "top_evidence": row["_best_evidence"],
                "similarity_score": round(avg_sim, 4),
            })

        matrix.sort(key=lambda r: r["similarity_score"], reverse=True)
        return matrix

    @staticmethod
    def _build_dataset_overlap(
        matrix: List[Dict[str, Any]],
    ) -> Dict[str, List[str]]:
        """Find datasets used by two or more papers.

        Returns:
            Mapping of dataset name → list of paper titles that used it.
            Only datasets appearing in 2+ papers are included.
        """
        ds_to_papers: Dict[str, List[str]] = {}
        for row in matrix:
            title = row.get("title", "Unknown")
            for ds in row.get("datasets", []):
                ds_key = ds.strip()
                if not ds_key:
                    continue
                ds_to_papers.setdefault(ds_key, [])
                if title not in ds_to_papers[ds_key]:
                    ds_to_papers[ds_key].append(title)

        # Only return datasets shared by 2+ papers
        return {ds: papers for ds, papers in ds_to_papers.items() if len(papers) >= 2}

    @staticmethod
    def _resolve_paper_link(chunk: Dict[str, Any]) -> str:
        metadata = chunk.get("metadata") or {}
        return (
            str(chunk.get("paper_link") or "").strip()
            or str(chunk.get("link") or "").strip()
            or str(chunk.get("url") or "").strip()
            or str(metadata.get("link") or "").strip()
            or str(metadata.get("url") or "").strip()
        )

    @staticmethod
    def _resolve_paper_doi(chunk: Dict[str, Any]) -> str:
        metadata = chunk.get("metadata") or {}
        doi = str(chunk.get("doi") or "").strip() or str(metadata.get("doi") or "").strip()
        if doi and not doi.lower().startswith("http"):
            return doi.replace("https://doi.org/", "").replace("http://doi.org/", "")
        return doi

    @staticmethod
    def _split_sentences(text: str) -> List[str]:
        if not text:
            return []
        clean = " ".join(text.replace("\n", " ").split())
        parts = re.split(r"(?<=[.!?])\s+", clean)
        return [p.strip() for p in parts if p.strip()]

    def _build_claim_snippet(
        self,
        text: str,
        evidence_sentence: str,
        max_sentences: int = 3,
    ) -> str:
        """Build a multi-line claim snippet centered on the evidence sentence."""
        sentences = self._split_sentences(text)
        if not sentences:
            return ""

        ev = " ".join((evidence_sentence or "").split()).strip()
        target_idx = -1
        if ev:
            ev_lower = ev.lower()
            for idx, sentence in enumerate(sentences):
                s_lower = sentence.lower()
                if ev_lower in s_lower or s_lower in ev_lower:
                    target_idx = idx
                    break

        if target_idx < 0:
            snippet_sents = sentences[:max_sentences]
        else:
            half = max(0, (max_sentences - 1) // 2)
            start = max(0, target_idx - half)
            end = min(len(sentences), start + max_sentences)
            start = max(0, end - max_sentences)
            snippet_sents = sentences[start:end]

        return "\n".join(snippet_sents)

    @staticmethod
    def _clean_sentence(sentence: str) -> str:
        """Remove noisy citation/header artifacts from a sentence."""
        if not sentence:
            return ""
        s = sentence.strip()
        s = re.sub(r"\bet\s+al\.?[,]?\s*\(?\d{4}\)?", "", s, flags=re.IGNORECASE)
        s = re.sub(r"\[(\d+|\d+\s*[-,]\s*\d+)\]", "", s)
        s = re.sub(r"\(\s*\d{4}\s*\)", "", s)
        s = re.sub(r"^(abstract|introduction|background|methods?|methodology|results?|discussion|conclusion)\s*[:\-]\s*", "", s, flags=re.IGNORECASE)
        s = re.sub(r"\s+", " ", s).strip(" -:;,")
        if s and s[0].islower():
            s = s[0].upper() + s[1:]
        return s

    @staticmethod
    def _is_noise_sentence(sentence: str) -> bool:
        if not sentence:
            return True
        s = sentence.strip()
        if len(s.split()) < 6:
            return True
        lower = s.lower()
        if lower.endswith(":"):
            return True
        if any(p in lower for p in ["copyright", "all rights reserved", "doi:", "arxiv:"]):
            return True
        return False

    def _build_clean_paragraph(
        self,
        text: str,
        evidence_sentence: str,
        min_sentences: int | None = None,
        max_sentences: int | None = None,
    ) -> tuple[str, int, int]:
        """Build clean readable paragraph span and return (text, start, end)."""
        min_s = min_sentences or self.PARAGRAPH_MIN_SENTENCES
        max_s = max_sentences or self.PARAGRAPH_MAX_SENTENCES

        raw_sentences = self._split_sentences(text)
        cleaned = [self._clean_sentence(s) for s in raw_sentences]
        cleaned = [s for s in cleaned if s and not self._is_noise_sentence(s)]
        if not cleaned:
            return "", 1, 1

        ev = " ".join((evidence_sentence or "").split()).strip().lower()
        target_idx = 0
        if ev:
            for idx, sent in enumerate(cleaned):
                low = sent.lower()
                if ev in low or low in ev:
                    target_idx = idx
                    break

        desired = max(min_s, min(max_s, 4))
        half = desired // 2
        start = max(0, target_idx - half)
        end = min(len(cleaned), start + desired)
        start = max(0, end - desired)

        while (end - start) < min_s and end < len(cleaned):
            end += 1
        while (end - start) < min_s and start > 0:
            start -= 1

        paragraph = " ".join(cleaned[start:end]).strip()
        if not self._is_coherent_window(cleaned[start:end]):
            window = self._best_contiguous_window(cleaned, min_s=min_s, max_s=max_s)
            paragraph = " ".join(window["sentences"]).strip()
            return paragraph, window["start"] + 1, window["end"]

        return paragraph, start + 1, end

    @staticmethod
    def _is_coherent_window(sentences: List[str]) -> bool:
        """Heuristic coherence check for sentence windows."""
        if len(sentences) <= 1:
            return True
        stop = {
            "the", "and", "for", "with", "this", "that", "from", "into", "using",
            "are", "was", "were", "has", "have", "had", "into", "over", "under",
        }

        def terms(s: str) -> set[str]:
            return {
                w.strip(".,;:()[]{}\"'`").lower()
                for w in s.split()
                if len(w.strip(".,;:()[]{}\"'`")) > 2 and w.strip(".,;:()[]{}\"'`").lower() not in stop
            }

        overlaps = []
        for i in range(len(sentences) - 1):
            a = terms(sentences[i])
            b = terms(sentences[i + 1])
            if not a or not b:
                overlaps.append(0.0)
                continue
            overlaps.append(len(a.intersection(b)) / max(1, len(a.union(b))))

        avg_overlap = sum(overlaps) / len(overlaps) if overlaps else 0.0
        return avg_overlap >= 0.05

    def _best_contiguous_window(
        self,
        sentences: List[str],
        min_s: int,
        max_s: int,
    ) -> Dict[str, Any]:
        """Fallback window chooser maximizing internal lexical coherence."""
        if not sentences:
            return {"sentences": [], "start": 0, "end": 0}

        best = {"score": -1.0, "sentences": sentences[:min_s], "start": 0, "end": min(len(sentences), min_s)}
        max_len = min(max_s, len(sentences))
        for win_len in range(min_s, max_len + 1):
            for start in range(0, len(sentences) - win_len + 1):
                end = start + win_len
                window = sentences[start:end]
                score = 1.0 if self._is_coherent_window(window) else 0.0
                if score > best["score"]:
                    best = {"score": score, "sentences": window, "start": start, "end": end}
        return best

    @staticmethod
    def _confidence_band(score: float) -> str:
        if score >= 0.75:
            return "High"
        if score >= 0.60:
            return "Medium"
        return "Low"

    @staticmethod
    def _section_preferences(sub_question: str) -> set[str]:
        sq = (sub_question or "").lower()
        base = {"Results", "Discussion"}
        if any(k in sq for k in ["method", "approach", "how", "technique"]):
            return base | {"Methodology", "Introduction"}
        if any(k in sq for k in ["result", "performance", "effective", "accuracy"]):
            return base | {"Methodology", "Conclusion"}
        if any(k in sq for k in ["challenge", "limitation", "risk", "issue"]):
            return base | {"Conclusion"}
        return {"Introduction", "Methodology", "Results", "Discussion", "Conclusion", "Related_work", "unknown"}

    @staticmethod
    def _normalize_section(section: str) -> str:
        if not section:
            return "unknown"
        s = str(section).strip().lower()
        for canonical, aliases in AnswerGenerator.SECTION_MAP.items():
            if any(alias in s for alias in aliases):
                return canonical.title()
        return "unknown"

    # ─── STEP 3: Section Validation (NEW METHODS) ────────────────────────────────
    
    METHODOLOGY_ALLOWED_SECTIONS = {
        "methodology", "method", "methods", "approach", "system design",
        "experimental setup", "implementation", "framework", "pipeline", "architecture"
    }
    
    IMPORTANT_FIELDS = [
        "contributions", "dataset", "methodology", "models", "metrics", "limitations"
    ]

    def _infer_section_from_content(self, text: str, labeled_section: str) -> str:
        """Infer TRUE section using explicit headers first, then strong cues."""
        if not text:
            return self._normalize_section(labeled_section)

        text_lower = text.lower()

        # Pre-check: trust labeled section if it's already meaningful
        normalized_label = self._normalize_section(labeled_section)
        if normalized_label not in {"unknown", "body"}:
            # Only override if very strong contradicting signal
            STRONG_RESULTS_SIGNALS = [
                "accuracy:", "f1:", "precision:", "recall:", "auc-roc",
                "mean average precision", "outperforms all baselines"
            ]
            if normalized_label != "Results" and any(
                s in text_lower for s in STRONG_RESULTS_SIGNALS
            ):
                return "Results"
            return normalized_label

        # Explicit override rules for section correction.
        if any(k in text_lower for k in ["in this paper", "we introduce"]):
            return "Introduction"
        if any(k in text_lower for k in ["we propose", "framework", "architecture"]):
            return "Methodology"
        if any(k in text_lower for k in ["results show", "evaluation"]):
            return "Results"
        if any(k in text_lower for k in ["limitation", "future work"]):
            return "Discussion"

        # Priority 1: explicit markdown/style headers
        if re.search(r"(^|\n)\s{0,3}(#\s*|##\s*|\d+\.?\s+)?introduction\b", text_lower):
            return "Introduction"
        if re.search(r"(^|\n)\s{0,3}(#\s*|##\s*|\d+\.?\s+)?(method|methods|methodology|approach|implementation)\b", text_lower):
            return "Methodology"
        if re.search(r"(^|\n)\s{0,3}(#\s*|##\s*|\d+\.?\s+)?(results|evaluation|experiments?|findings?)\b", text_lower):
            return "Results"
        if re.search(r"(^|\n)\s{0,3}(#\s*|##\s*|\d+\.?\s+)?(discussion|analysis|limitations?)\b", text_lower):
            return "Discussion"
        if re.search(r"(^|\n)\s{0,3}(#\s*|##\s*|\d+\.?\s+)?(conclusion|future work|summary)\b", text_lower):
            return "Conclusion"

        # Priority 2: strong results cues (more specific than weak methodology words)
        results_cues = [
            "accuracy", "precision", "recall", "f1", "benchmark", "outperform", "state-of-the-art",
            "experimental results", "evaluation results", "performance on"
        ]
        if any(cue in text_lower for cue in results_cues):
            return "Results"

        # Priority 3: strong introduction cues
        intro_cues = [
            "problem statement", "research question", "motivation", "this paper addresses", "background"
        ]
        if any(cue in text_lower for cue in intro_cues):
            return "Introduction"

        # Priority 4: strong methodology cues
        methodology_cues = [
            "algorithm", "pseudo-code", "training process", "hyperparameter", "implementation details",
            "network architecture", "loss function", "gradient"
        ]
        if any(cue in text_lower for cue in methodology_cues):
            return "Methodology"

        # Priority 5: trust labeled metadata section
        return self._normalize_section(labeled_section)

    def _resolve_true_section(self, chunk: Dict[str, Any]) -> tuple[str, bool]:
        """
        Resolve TRUE section using labeled + inferred.
        Returns (true_section, was_corrected).
        """
        labeled_section = self._normalize_section(
            chunk.get("metadata", {}).get("section") or chunk.get("section", "unknown")
        )
        text = chunk.get("text", "")
        inferred_section = self._infer_section_from_content(text, labeled_section)
        
        was_corrected = labeled_section.lower() != inferred_section.lower()
        return inferred_section, was_corrected

    def _is_methodology_subquestion(self, subq: str) -> bool:
        """Detect if sub-question is methodology-focused."""
        sq = (subq or "").lower()
        methodology_keywords = [
            "method", "approach", "how", "technique", "algorithm", "procedure",
            "framework", "pipeline", "system design", "architecture"
        ]
        return any(k in sq for k in methodology_keywords)

    def _section_allowed_for_subquestion(self, section: str, subq: str) -> bool:
        """Balanced section gating: always allow outcome sections."""
        if (section or "").lower() in {"results", "discussion", "conclusion"}:
            return True
        if not self._is_methodology_subquestion(subq):
            # Non-methodology sub-questions accept any section
            return True
        
        # Methodology sub-questions ONLY accept methodology-related sections
        section_lower = (section or "unknown").lower()
        return any(allowed in section_lower for allowed in self.METHODOLOGY_ALLOWED_SECTIONS)

    def _extract_heading_from_chunk(self, chunk: Dict[str, Any]) -> str:
        """Extract nearest heading from chunk metadata."""
        metadata = chunk.get("metadata") or {}
        heading = (
            metadata.get("heading") or
            metadata.get("subheading") or
            metadata.get("nearest_heading") or
            ""
        )
        return heading.strip()

    def _extract_important_points(self, chunk: Dict[str, Any]) -> Dict[str, Any]:
        """Extract 6 important fields from chunk."""
        text = chunk.get("text", "").lower()
        
        result = {
            "contributions": [],
            "dataset": [],
            "methodology": [],
            "models": [],
            "metrics": [],
            "limitations": []
        }
        
        # Extract contributions
        if any(w in text for w in ["propose", "introduce", "present", "novel", "contribution"]):
            result["contributions"].append(chunk.get("text", "")[:100])
        
        # Extract dataset references
        if any(w in text for w in ["dataset", "benchmark", "corpus", "data source", "collection"]):
            result["dataset"].append(chunk.get("text", "")[:100])
        
        # Extract methodology
        if any(w in text for w in ["method", "approach", "algorithm", "procedure", "pipeline"]):
            result["methodology"].append(chunk.get("text", "")[:100])
        
        # Extract model references
        if any(w in text for w in ["model", "network", "architecture", "framework"]):
            result["models"].append(chunk.get("text", "")[:100])
        
        # Extract metrics/performance
        if any(w in text for w in ["accuracy", "f1", "score", "metric", "performance", "evaluation"]):
            result["metrics"].append(chunk.get("text", "")[:100])
        
        # Extract limitations
        if any(w in text for w in ["limitation", "challenge", "future work", "gap", "drawback"]):
            result["limitations"].append(chunk.get("text", "")[:100])
        
        return result

    def _merge_paper_evidence(self, units: List[Dict[str, Any]]) -> Dict[str, Dict[str, Any]]:
        """
        Consolidate all evidence units by paper.
        Returns: {paper_id: {paper_id, title, sections, important_sections, traceable_citations}}
        """
        by_paper: Dict[str, Dict[str, Any]] = {}
        
        for unit in units:
            paper_id = unit.get("paper_id", "unknown")
            if paper_id not in by_paper:
                by_paper[paper_id] = {
                    "paper_id": paper_id,
                    "paper_title": unit.get("paper_title", "Unknown"),
                    "paper_year": unit.get("paper_year", "N/A"),
                    "sections": set(),
                    "important_sections": {},
                    "traceable_citations": [],
                }
            
            section = unit.get("section", "unknown")
            by_paper[paper_id]["sections"].add(section)
            
            # Track important points
            if "important_points" in unit:
                for field in self.IMPORTANT_FIELDS:
                    if field not in by_paper[paper_id]["important_sections"]:
                        by_paper[paper_id]["important_sections"][field] = []
                    points = unit.get("important_points", {}).get(field, [])
                    by_paper[paper_id]["important_sections"][field].extend(points)
            
            # Build traceable citation
            traceable = {
                "paper_title": unit.get("paper_title", "Unknown"),
                "section": section,
                "heading": unit.get("nearest_heading", ""),
                "location": f"sentences {unit.get('location_start', 1)}–{unit.get('location_end', 1)}",
                "text": unit.get("text", ""),
                "claim": unit.get("claim", "")
            }
            by_paper[paper_id]["traceable_citations"].append(traceable)
        
        # Convert sets to lists
        for paper_id in by_paper:
            by_paper[paper_id]["sections"] = list(by_paper[paper_id]["sections"])
        
        return by_paper

    def _quality_gate(self, merged_evidence: Dict[str, Dict[str, Any]]) -> Dict[str, Any]:
        """
        Pre-output validation.
        Returns: {status, issues, gaps}
        """
        issues = []
        gaps = []
        
        if not merged_evidence:
            return {
                "status": "rejected",
                "issues": ["No evidence units found"],
                "gaps": ["Complete absence of retrieved evidence"]
            }
        
        # Check section coverage (should span multiple sections)
        all_sections = set()
        for paper_data in merged_evidence.values():
            all_sections.update(paper_data.get("sections", []))
        
        if len(all_sections) < 2:
            gaps.append(f"Low section coverage: only {len(all_sections)} section(s) represented")
        
        # Check paper diversity
        num_papers = len(merged_evidence)
        if num_papers < 2:
            gaps.append(f"Low paper diversity: only {num_papers} paper(s)")
        
        # Check for missing traceability
        for paper_id, paper_data in merged_evidence.items():
            if not paper_data.get("traceable_citations"):
                issues.append(f"Paper {paper_id}: missing traceability")
        
        # Check for duplicate papers (shouldn't happen with merge, but check anyway)
        titles = [p.get("paper_title", "") for p in merged_evidence.values()]
        if len(titles) != len(set(titles)):
            issues.append("Duplicate papers detected in output")
        
        status = "accepted" if not issues and len(all_sections) >= 2 else "accepted_with_warnings"
        if issues:
            status = "rejected"
        
        return {
            "status": status,
            "issues": issues,
            "gaps": gaps if gaps else None,
            "section_coverage": list(all_sections),
            "paper_count": num_papers
        }

    @staticmethod
    def _lexical_similarity(a: str, b: str) -> float:
        ta = {
            t.strip(".,;:()[]{}\"'`").lower()
            for t in (a or "").split()
            if len(t.strip(".,;:()[]{}\"'`")) > 2
        }
        tb = {
            t.strip(".,;:()[]{}\"'`").lower()
            for t in (b or "").split()
            if len(t.strip(".,;:()[]{}\"'`")) > 2
        }
        if not ta or not tb:
            return 0.0
        inter = len(ta.intersection(tb))
        union = len(ta.union(tb))
        return inter / union if union else 0.0

    @staticmethod
    def _keyword_overlap(a: str, b: str) -> float:
        """Normalized keyword overlap for soft scoring."""
        ta = {
            t.strip(".,;:()[]{}\"'`").lower()
            for t in (a or "").split()
            if len(t.strip(".,;:()[]{}\"'`")) > 2
        }
        tb = {
            t.strip(".,;:()[]{}\"'`").lower()
            for t in (b or "").split()
            if len(t.strip(".,;:()[]{}\"'`")) > 2
        }
        if not ta or not tb:
            return 0.0
        return len(ta.intersection(tb)) / max(1, min(len(ta), len(tb)))

    def _section_weight(self, sub_question: str, section: str) -> float:
        sq = (sub_question or "").lower()
        sec = (section or "unknown").lower()
        if any(k in sq for k in ["method", "approach", "how"]):
            return 1.20 if "method" in sec else 1.0
        if any(k in sq for k in ["result", "performance", "accuracy", "effective"]):
            return 1.20 if "result" in sec else 1.0
        if any(k in sq for k in ["challenge", "limitation", "issue", "risk"]):
            return 1.20 if ("discussion" in sec or "conclusion" in sec) else 1.0
        return 1.0

    def _infer_intent(self, sub_question: str, provided_intent: str = "") -> str:
        intent = (provided_intent or "").strip().lower()
        if intent in self.INTENT_KEYWORDS:
            return intent
        sq = (sub_question or "").lower()
        for k, words in self.INTENT_KEYWORDS.items():
            if any(w in sq for w in words):
                return k
        return "methodology"

    def _chunk_matches_intent(self, chunk_text: str, intent: str) -> bool:
        if not chunk_text:
            return False
        text = chunk_text.lower()
        keywords = self.INTENT_KEYWORDS.get(intent, [])
        if not keywords:
            return True

        # Require explicit dataset grounding for dataset-focused sub-questions.
        if intent == "dataset":
            has_dataset_keyword = any(w in text for w in keywords)
            has_only_detection = any(w in text for w in self.INTENT_KEYWORDS.get("detection", [])) and not has_dataset_keyword
            return has_dataset_keyword and not has_only_detection

        return any(w in text for w in keywords)

    @staticmethod
    def _is_dataset_subquestion(sub_question: str) -> bool:
        sq = (sub_question or "").lower()
        return any(k in sq for k in ["dataset", "data", "training"])

    def _dataset_signal_score(self, chunk_text: str) -> float:
        text = (chunk_text or "").lower()
        if not text:
            return 0.0
        hits = sum(1 for s in self.DATASET_SIGNALS if s in text)
        return min(1.0, hits / 3.0)

    def _is_background_drift(self, sub_question: str, chunk_text: str, user_level: str) -> bool:
        level = (user_level or "auto").lower()
        if level not in {"intermediate", "advanced"}:
            return False

        sq = (sub_question or "").lower()
        if any(k in sq for k in ["overview", "introduction", "basic", "what is", "iot"]):
            return False

        text = (chunk_text or "").lower()
        return any(term in text for term in self.BACKGROUND_DRIFT_TERMS)

    @staticmethod
    def _simplify_text(text: str) -> str:
        if not text:
            return ""
        s = text.lower()
        s = re.sub(r"[^a-z0-9\s]", " ", s)
        s = re.sub(r"\s+", " ", s).strip()
        return s

    def _expand_query_forms(self, sub_question: str) -> List[str]:
        """Build expanded query forms (original + synonym-expanded + simplified)."""
        base = (sub_question or "").strip()
        if not base:
            return []

        synonyms = {
            "machine learning": ["deep learning", "ml models"],
            "deep learning": ["neural network", "cnn", "model"],
            "performance": ["accuracy", "results", "evaluation"],
            "method": ["approach", "technique", "pipeline"],
            "challenges": ["limitations", "issues", "difficulties"],
            "segmentation": ["partition", "delineation", "extraction"],
        }

        expanded = [base]
        expanded_text = base
        lower = base.lower()
        for key, vals in synonyms.items():
            if key in lower:
                expanded_text += " " + " ".join(vals)
        expanded.append(expanded_text)
        expanded.append(self._simplify_text(base))

        # Keep unique, non-empty forms
        unique: List[str] = []
        seen = set()
        for q in expanded:
            nq = q.strip()
            if not nq:
                continue
            if nq not in seen:
                seen.add(nq)
                unique.append(nq)
        return unique

    def _best_scored_contiguous_window(
        self,
        sentences: List[str],
        scores: List[float],
        min_s: int,
        max_s: int,
    ) -> Dict[str, Any]:
        if not sentences:
            return {"sentences": [], "start": 0, "end": 0, "score": 0.0}

        best = {
            "sentences": sentences[:min_s],
            "start": 0,
            "end": min(len(sentences), min_s),
            "score": -1.0,
        }
        max_len = min(max_s, len(sentences))
        for win_len in range(min_s, max_len + 1):
            for start in range(0, len(sentences) - win_len + 1):
                end = start + win_len
                window = sentences[start:end]
                window_scores = scores[start:end]
                coherence_bonus = 0.1 if self._is_coherent_window(window) else 0.0
                avg_score = (sum(window_scores) / max(1, len(window_scores))) + coherence_bonus
                if avg_score > best["score"]:
                    best = {
                        "sentences": window,
                        "start": start,
                        "end": end,
                        "score": avg_score,
                    }
        return best

    def _build_evidence_paragraph(
        self,
        sub_question: str,
        text: str,
        evidence_extractor,
    ) -> Dict[str, Any]:
        if evidence_extractor and hasattr(evidence_extractor, "select_best_paragraph"):
            selected = evidence_extractor.select_best_paragraph(
                query=sub_question,
                text=text,
                min_similarity=0.0,
                min_sentences=self.PARAGRAPH_MIN_SENTENCES,
                max_sentences=self.PARAGRAPH_MAX_SENTENCES,
            )
            paragraph = (selected.get("best_paragraph") or "").strip()
            if paragraph:
                all_scored = selected.get("all_sentences") or []
                best_score = float(selected.get("best_score", 0.0) or 0.0)
                best_sentence = ""
                if all_scored:
                    best_sentence = max(all_scored, key=lambda x: float(x[1] or 0.0))[0]
                return {
                    "paragraph": paragraph,
                    "start": int(selected.get("start", 1) or 1),
                    "end": int(selected.get("end", 1) or 1),
                    "best_sentence": best_sentence,
                    "best_score": best_score,
                }

        sentences = [self._clean_sentence(s) for s in self._split_sentences(text)]
        sentences = [s for s in sentences if s and not self._is_noise_sentence(s)]
        if not sentences:
            return {
                "paragraph": "",
                "start": 1,
                "end": 1,
                "best_sentence": "",
                "best_score": 0.0,
            }

        scores: List[float] = []
        for s in sentences:
            scores.append(self._lexical_similarity(sub_question, s))

        ranked_ids = sorted(range(len(sentences)), key=lambda i: scores[i], reverse=True)
        top_ids = ranked_ids[: min(len(ranked_ids), self.PARAGRAPH_MAX_SENTENCES)]
        coherent_ids: List[int] = []
        for idx in top_ids:
            if len(coherent_ids) >= self.PARAGRAPH_MAX_SENTENCES:
                break
            candidate = coherent_ids + [idx]
            candidate_sents = [sentences[i] for i in sorted(candidate)]
            if len(candidate_sents) <= 1 or self._is_coherent_window(candidate_sents):
                coherent_ids.append(idx)

        coherent_ids = sorted(coherent_ids)
        contiguous = bool(coherent_ids) and (coherent_ids[-1] - coherent_ids[0] + 1 == len(coherent_ids))
        coherent_ok = len(coherent_ids) >= self.PARAGRAPH_MIN_SENTENCES and self._is_coherent_window([sentences[i] for i in coherent_ids])

        if contiguous or coherent_ok:
            selected = coherent_ids
            if len(selected) < self.PARAGRAPH_MIN_SENTENCES:
                window = self._best_scored_contiguous_window(
                    sentences,
                    scores,
                    self.PARAGRAPH_MIN_SENTENCES,
                    self.PARAGRAPH_MAX_SENTENCES,
                )
                selected = list(range(window["start"], window["end"]))
        else:
            window = self._best_scored_contiguous_window(
                sentences,
                scores,
                self.PARAGRAPH_MIN_SENTENCES,
                self.PARAGRAPH_MAX_SENTENCES,
            )
            selected = list(range(window["start"], window["end"]))

        if not selected:
            return {
                "paragraph": "",
                "start": 1,
                "end": 1,
                "best_sentence": "",
                "best_score": 0.0,
            }

        paragraph = " ".join(sentences[i] for i in selected).strip()
        best_idx = max(selected, key=lambda i: scores[i])
        return {
            "paragraph": paragraph,
            "start": selected[0] + 1,
            "end": selected[-1] + 1,
            "best_sentence": sentences[best_idx],
            "best_score": scores[best_idx],
        }

    def _build_subquestion_conclusion(self, sub_question: str, units: List[Dict[str, Any]]) -> str:
        if not units:
            return "Insufficient evidence to draw a conclusion for this sub-question."

        paper_names = list({u.get("paper_title", "Unknown")[:35] for u in units})
        sections = list({u.get("section", "unknown") for u in units})
        avg_conf = sum(float(u.get("confidence", 0)) for u in units) / max(1, len(units))

        return (
            f"Evidence drawn from {len(paper_names)} paper(s) "
            f"({'; '.join(paper_names[:3])}{'...' if len(paper_names) > 3 else ''}) "
            f"across sections: {', '.join(sections)}. "
            f"Average evidence confidence: {avg_conf:.2f}. "
            f"See the AI Research Summary section for synthesized interpretation."
        )

    def _extract_signal_sentences(self, text: str, keywords: List[str], max_items: int = 2) -> List[str]:
        if not text:
            return []
        sents = [self._clean_sentence(s) for s in self._split_sentences(text)]
        sents = [s for s in sents if s and not self._is_noise_sentence(s)]
        hits: List[str] = []
        for s in sents:
            low = s.lower()
            if any(k in low for k in keywords):
                hits.append(s)
                if len(hits) >= max_items:
                    break
        return hits

    def _build_paper_profiles(self, chunks: List[Dict[str, Any]]) -> Dict[str, Dict[str, Any]]:
        """Create paper-level structured facets for downstream reasoning."""
        profiles: Dict[str, Dict[str, Any]] = {}
        for c in chunks:
            pid = str(c.get("paper_id") or "")
            if not pid:
                continue
            if pid not in profiles:
                profiles[pid] = {
                    "paper_id": pid,
                    "paper_title": c.get("paper_title", "Unknown"),
                    "paper_year": c.get("paper_year", "N/A"),
                    "dataset": [],
                    "method": [],
                    "results": [],
                    "application": [],
                    "chunks": [],
                }

            text = c.get("text", "")
            profiles[pid]["dataset"].extend(
                self._extract_signal_sentences(
                    text,
                    ["dataset", "benchmark", "corpus", "training data", "data collection"],
                )
            )
            profiles[pid]["method"].extend(
                self._extract_signal_sentences(
                    text,
                    ["method", "approach", "framework", "pipeline", "algorithm", "architecture"],
                )
            )
            profiles[pid]["results"].extend(
                self._extract_signal_sentences(
                    text,
                    ["result", "accuracy", "f1", "precision", "recall", "outperform", "evaluation"],
                )
            )
            profiles[pid]["application"].extend(
                self._extract_signal_sentences(
                    text,
                    ["application", "use case", "deployment", "real-world", "practical", "scenario"],
                )
            )
            profiles[pid]["chunks"].append(c)

        for p in profiles.values():
            for facet in ["dataset", "method", "results", "application"]:
                seen = set()
                unique = []
                for v in p[facet]:
                    key = v.strip().lower()
                    if key and key not in seen:
                        seen.add(key)
                        unique.append(v)
                p[facet] = unique[:4]
        return profiles

    def _build_grounded_comparison(self, sub_question: str, paper_profiles: Dict[str, Dict[str, Any]]) -> str:
        if not paper_profiles:
            return "Insufficient evidence for cross-paper comparison."

        lines = []
        profiles = list(paper_profiles.values())[:5]

        # Per-paper method statement (cite actual extracted sentences)
        method_lines = []
        for p in profiles:
            name = f"{p.get('paper_title', 'Unknown')[:40]} ({p.get('paper_year', 'N/A')})"
            methods = p.get("method", [])
            if methods:
                method_lines.append(f"  • {name}: {methods[0][:120]}")

        # Per-paper result statement
        result_lines = []
        for p in profiles:
            name = f"{p.get('paper_title', 'Unknown')[:40]} ({p.get('paper_year', 'N/A')})"
            results = p.get("results", [])
            if results:
                result_lines.append(f"  • {name}: {results[0][:120]}")

        # Agreement or disagreement statement
        all_units = [
            u for p in profiles for u in p.get("chunks", [])
        ]
        conflicts = ConflictDetector.detect_conflicts(all_units)

        if method_lines:
            lines.append(f"Method approaches across {len(profiles)} paper(s):")
            lines.extend(method_lines)
        if result_lines:
            lines.append(f"\nReported outcomes:")
            lines.extend(result_lines)
        if conflicts:
            c = conflicts[0]
            lines.append(
                f"\nConflict: {c.get('a', {}).get('paper_title', 'Paper A')[:30]} vs "
                f"{c.get('b', {}).get('paper_title', 'Paper B')[:30]} on overlapping claims "
                f"(type: {c.get('type', 'unknown')}, strength: {c.get('strength', 0):.2f})"
            )
        else:
            lines.append(
                f"\nConsensus: The {len(profiles)} paper(s) are directionally "
                f"aligned with no strongly incompatible claims detected."
            )

        return "\n".join(lines) if lines else "No comparison data available."

    def _build_evidence_unit(
        self,
        sub_question: str,
        chunk: Dict[str, Any],
        evidence_extractor,
        subquery_similarity: float,
    ) -> Dict[str, Any] | None:
        text = chunk.get("text", "")
        if not text:
            return None

        evidence_sentence = chunk.get("evidence_sentence", "")
        evidence_score = float(chunk.get("evidence_score", 0.0) or 0.0)
        similarity_score = float(chunk.get("similarity_score", 0.0) or 0.0)
        paragraph_info = self._build_evidence_paragraph(sub_question, text, evidence_extractor)
        snippet = paragraph_info.get("paragraph", "")
        sentence_start = int(paragraph_info.get("start", 1))
        sentence_end = int(paragraph_info.get("end", 1))
        if not snippet:
            return None

        evidence_sentence = paragraph_info.get("best_sentence", evidence_sentence)
        evidence_score = max(evidence_score, float(paragraph_info.get("best_score", 0.0) or 0.0))

        verification_score = float(
            chunk.get("verification_score", chunk.get("confidence_score", similarity_score)) or similarity_score
        )

        metadata = chunk.get("metadata") or {}
        labeled_section = self._normalize_section(metadata.get("section") or chunk.get("section", "unknown"))
        
        # STEP 3: Resolve TRUE section with correction tracking
        true_section, section_corrected = self._resolve_true_section(chunk)
        
        # STEP 3: Soft section gating (penalty, not hard-drop)
        section_penalty = 0.0
        if not self._section_allowed_for_subquestion(true_section, sub_question):
            section_penalty = 0.12
        
        section_weight = self._section_weight(sub_question, true_section)

        confidence = max(
            0.0,
            min(
                1.0,
                (self.CONFIDENCE_W1 * subquery_similarity)
                + (self.CONFIDENCE_W2 * evidence_score)
                + (self.CONFIDENCE_W3 * verification_score),
            ),
        )
        keyword_overlap = float(
            chunk.get("keyword_overlap", self._keyword_overlap(sub_question, snippet)) or 0.0
        )
        base_score = (
            (0.4 * float(chunk.get("rrf_score", 0.0) or 0.0))
            + (0.3 * subquery_similarity)
            + (0.2 * evidence_score)
            + (0.1 * keyword_overlap)
        )
        similarity_penalty = 0.0
        if subquery_similarity < self.SUBQUERY_HARD_GATE_THRESHOLD:
            similarity_penalty = (self.SUBQUERY_HARD_GATE_THRESHOLD - subquery_similarity) * 0.25

        final_score = max(
            0.0,
            min(
                1.0,
                base_score - similarity_penalty - section_penalty,
            ),
        )

        # Extract traceability metadata
        nearest_heading = self._extract_heading_from_chunk(chunk)
        important_points = self._extract_important_points(chunk)

        return {
            "chunk_id": chunk.get("chunk_id", ""),
            "paper_id": chunk.get("paper_id", ""),
            "paper_title": chunk.get("paper_title", "Unknown"),
            "paper_year": chunk.get("paper_year", "N/A"),
            "paper_doi": self._resolve_paper_doi(chunk),
            "paper_link": self._resolve_paper_link(chunk),
            "section": true_section,
            "section_corrected": section_corrected,
            "labeled_section": labeled_section,
            "nearest_heading": nearest_heading,
            "location_start": sentence_start,
            "location_end": sentence_end,
            "relevance": similarity_score,
            "evidence_score": evidence_score,
            "verification_score": verification_score,
            "final_score": final_score,
            "subquery_similarity": subquery_similarity,
            "confidence": confidence,
            "confidence_band": self._confidence_band(confidence),
            "text": snippet,
            "claim": evidence_sentence or snippet,
            "important_points": important_points,
        }
    
    def generate_answer(self, query: str, retrieved_chunks: List[Dict[str, Any]]) -> str:
        """
        Generate an answer from retrieved chunks.
        
        For MVP: concatenate chunks into structured answer with citations.
        
        Args:
            query: Original user query
            retrieved_chunks: List of retrieved chunk objects
            
        Returns:
            Formatted answer with citations
        """
        if not retrieved_chunks:
            return "I could not find relevant information to answer your question."
        
        try:
            answer = self._build_structured_answer(query, retrieved_chunks)
            return answer
        except Exception as e:
            print(f"✗ Error generating answer: {e}")
            return "Error generating answer from retrieved chunks."
    
    def _build_structured_answer(self, query: str, chunks: List[Dict[str, Any]]) -> str:
        """
        Build structured answer from chunks with citations.
        
        Args:
            query: User query
            chunks: Retrieved chunks
            
        Returns:
            Formatted answer
        """
        answer = f"\nQuestion: {query}\n\n"
        answer += "="*80 + "\n"
        answer += "ANSWER\n"
        answer += "="*80 + "\n\n"
        
        # Collect evidence by paper
        evidence_by_paper = {}
        for chunk in chunks:
            paper_key = f"{chunk['paper_title']} ({chunk['paper_year']})"
            if paper_key not in evidence_by_paper:
                evidence_by_paper[paper_key] = []
            evidence_by_paper[paper_key].append(chunk)
        
        # Build answer with citations
        answer_text = "Based on the retrieved research, "
        
        # Add first chunk as main evidence
        if chunks:
            first_chunk = chunks[0]
            answer_text += f"{first_chunk['text']} "
            answer_text += f"[{first_chunk['paper_title']}, {first_chunk['paper_year']}]\n\n"
        
        answer += answer_text
        answer += self._format_citations(evidence_by_paper)
        
        return answer
    
    def _format_citations(self, evidence_by_paper: Dict[str, List[Dict[str, Any]]]) -> str:
        """
        Format citations section.
        
        Args:
            evidence_by_paper: Dictionary of evidence grouped by paper
            
        Returns:
            Formatted citations
        """
        citations = "="*80 + "\n"
        citations += "EVIDENCE CITATIONS\n"
        citations += "="*80 + "\n\n"
        
        for paper_key, chunks in evidence_by_paper.items():
            citations += f"📄 {paper_key}\n"
            scores = ", ".join([f"{c.get('similarity_score', 0):.4f}" for c in chunks])
            citations += f"   Relevance Scores: {scores}\n"
            citations += f"   Evidence:\n"
            for i, chunk in enumerate(chunks, 1):
                chunk_text = chunk.get('text', '')[:80]
                citations += f"     {i}. {chunk_text}...\n"
            citations += "\n"
        
        return citations
    
    def format_final_output(self, answer: str, retrieved_chunks: List[Dict[str, Any]]) -> str:
        """
        Format final output with answer and evidence.
        
        Args:
            answer: Generated answer
            retrieved_chunks: Retrieved chunks
            
        Returns:
            Formatted final output
        """
        output = answer
        output += "\n" + "="*80 + "\n"
        output += "RETRIEVED CHUNKS (FOR DEBUGGING)\n"
        output += "="*80 + "\n\n"
        
        for i, chunk in enumerate(retrieved_chunks, 1):
            output += f"Chunk {i}:\n"
            output += f"  Paper: {chunk['paper_title']} ({chunk['paper_year']})\n"
            output += f"  Similarity: {chunk['similarity_score']:.4f}\n"
            output += f"  Text: {chunk['text']}\n\n"
        
        return output
    
    def generate_grouped_answer(
        self, 
        plan: Dict[str, Any], 
        chunks: List[Dict[str, Any]]
    ) -> str:
        """
        Generate grouped answer organized by sub-questions (Stage 3).
        
        Takes the decomposed plan from PlannerAgent and retrieved chunks,
        then organizes the output by sub-question with claims and evidence.
        
        Args:
            plan: Dictionary with main_question, sub_questions, search_queries
            chunks: Retrieved chunks from multi_retrieve
            
        Returns:
            Formatted answer grouped by sub-question
        """
        main_question = plan.get("main_question", "")
        sub_questions = plan.get("sub_questions", [])
        resolved_user_level = (plan.get("resolved_user_level") or "auto").lower()
        subquestion_intents = plan.get("subquestion_intents") or {}
        
        if not chunks:
            return "I could not find relevant information to answer your question."
        
        output = f"\n{'='*80}\n"
        output += f"AGENTIC RAG RESPONSE\n"
        output += f"{'='*80}\n\n"
        output += f"📝 Main Question: {main_question}\n\n"

        analysis_data: Dict[str, Any] = {
            "query": main_question,
            "generated_at": "",
            "sub_questions": [],
            "references": [],
            "final_summary": "",
            "stats": {},
        }
        
        # Coverage-first assignment (soft scoring, no hard filtering)
        try:
            chunk_assignments = self._assign_chunks_to_subquestions(
                sub_questions,
                chunks,
                subquestion_intents=subquestion_intents,
            )
        except TypeError:
            chunk_assignments = self._assign_chunks_to_subquestions(sub_questions, chunks)

        # Adaptive retry (generation-side): broaden assignment if usable evidence is weak.
        min_total_target = max(len(sub_questions) * self.MIN_CHUNKS_PER_SUBQ, self.MIN_CHUNKS_PER_SUBQ)
        usable_now = sum(
            1
            for sq in sub_questions
            for c in chunk_assignments.get(sq, [])
            if float(c.get("subquery_similarity", 0.0) or 0.0) >= 0.50
        )
        if usable_now < min_total_target:
            try:
                retry_assignments = self._assign_chunks_to_subquestions(
                    sub_questions,
                    chunks,
                    adaptive_round=1,
                    subquestion_intents=subquestion_intents,
                )
            except TypeError:
                # Backward compatibility for monkeypatched/stubbed callables that
                # still expose the legacy 2-arg signature.
                retry_assignments = self._assign_chunks_to_subquestions(sub_questions, chunks)
            for sq in sub_questions:
                merged = chunk_assignments.get(sq, []) + retry_assignments.get(sq, [])
                dedup: Dict[str, Dict[str, Any]] = {}
                for c in merged:
                    cid = str(c.get("chunk_id", ""))
                    if not cid:
                        continue
                    if cid not in dedup or float(c.get("final_score", 0.0) or 0.0) > float(dedup[cid].get("final_score", 0.0) or 0.0):
                        dedup[cid] = c
                chunk_assignments[sq] = sorted(
                    dedup.values(),
                    key=lambda x: float(x.get("final_score", 0.0) or 0.0),
                    reverse=True,
                )

        evidence_extractor = None
        try:
            from src.evidence.extractor import EvidenceExtractor
            evidence_extractor = EvidenceExtractor()
        except Exception:
            evidence_extractor = None
        
        global_top_chunks = sorted(
            chunks,
            key=lambda c: float(
                c.get("rrf_score", c.get("final_score", c.get("hybrid_score", c.get("similarity_score", 0.0))))
                or 0.0
            ),
            reverse=True,
        )

        embedder = None
        chunk_embeddings: List[Any] = []
        try:
            from src.embeddings.embedder import get_shared_embedder
            embedder = get_shared_embedder()
            chunk_embeddings = [embedder.embed_text(c.get("text", "")) for c in chunks]
        except Exception:
            embedder = None
            chunk_embeddings = []

        # Generate answer for each sub-question
        for i, sub_q in enumerate(sub_questions, 1):
            output += f"🔹 Sub-question: {sub_q}\n\n"
            subq_intent = self._infer_intent(sub_q, subquestion_intents.get(sub_q, ""))
            subq_data: Dict[str, Any] = {
                "question": sub_q,
                "intent": subq_intent,
                "debug": {},
                "papers": [],
                "conflicts": [],
                "comparison_text": "",
                "mini_summary": "",
            }
            
            assigned_chunks = chunk_assignments.get(sub_q, [])

            # Deduplicate per sub-question by chunk_id (avoid duplication explosion).
            dedup_assigned: Dict[str, Dict[str, Any]] = {}
            for chunk in assigned_chunks:
                cid = str(chunk.get("chunk_id", ""))
                if not cid:
                    continue
                score = float(chunk.get("subquery_similarity", 0.0) or 0.0)
                if cid not in dedup_assigned or score > float(dedup_assigned[cid].get("subquery_similarity", 0.0) or 0.0):
                    dedup_assigned[cid] = chunk
            assigned_chunks = list(dedup_assigned.values())

            dataset_subq = self._is_dataset_subquestion(sub_q)
            rescored_chunks: List[Dict[str, Any]] = []
            for chunk in assigned_chunks:
                text = chunk.get("text", "")
                if not text:
                    continue

                sq_score = float(chunk.get("subquery_similarity", 0.0) or 0.0)
                evidence_score = float(chunk.get("evidence_score", 0.0) or 0.0)
                rrf = float(chunk.get("rrf_score", 0.0) or 0.0)
                kw_overlap = self._keyword_overlap(sub_q, text)

                penalty = 0.0
                if sq_score < 0.60:
                    penalty += (0.60 - sq_score) * 0.35
                if self._is_background_drift(sub_q, text, resolved_user_level):
                    penalty += 0.15

                if dataset_subq:
                    ds_signal = self._dataset_signal_score(text)
                    if ds_signal <= 0.0:
                        penalty += 0.25
                    else:
                        sq_score = min(1.0, sq_score + 0.10 * ds_signal)

                final_score = (
                    (0.4 * rrf)
                    + (0.3 * sq_score)
                    + (0.2 * evidence_score)
                    + (0.1 * kw_overlap)
                    - penalty
                )

                rescored_chunks.append({
                    **chunk,
                    "subquery_similarity": sq_score,
                    "keyword_overlap": kw_overlap,
                    "penalty": penalty,
                    "final_score": final_score,
                    "sub_question": sub_q,
                })

            rescored_chunks.sort(key=lambda c: float(c.get("final_score", 0.0) or 0.0), reverse=True)

            # Coverage guarantee with multi-stage fallback.
            filtered_chunks = list(rescored_chunks[: self.MAX_CHUNKS_PER_SUBQ])
            fallback_triggered = False
            fallback_stages_used: List[str] = []

            if len(filtered_chunks) < self.MIN_CHUNKS_PER_SUBQ:
                fallback_triggered = True

                # Stage 1: Include lower-ranked RRF results
                stage1 = sorted(
                    rescored_chunks,
                    key=lambda x: float(x.get("rrf_score", 0.0) or 0.0),
                    reverse=True,
                )
                if stage1:
                    fallback_stages_used.append("stage1_lower_ranked_rrf")
                for c in stage1:
                    if len(filtered_chunks) >= self.MIN_CHUNKS_PER_SUBQ:
                        break
                    if c not in filtered_chunks:
                        filtered_chunks.append(c)

                # Stage 2: Relax similarity thresholds
                stage2 = [
                    c for c in rescored_chunks
                    if float(c.get("subquery_similarity", 0.0) or 0.0) >= 0.35
                ]
                if stage2:
                    fallback_stages_used.append("stage2_relaxed_similarity")
                for c in stage2:
                    if len(filtered_chunks) >= self.MIN_CHUNKS_PER_SUBQ:
                        break
                    if c not in filtered_chunks:
                        filtered_chunks.append(c)

                # Stage 3: Use global chunk pool
                if len(filtered_chunks) < self.MIN_CHUNKS_PER_SUBQ:
                    fallback_stages_used.append("stage3_global_pool")
                    global_candidates = []
                    for gc in global_top_chunks:
                        text = gc.get("text", "")
                        if not text:
                            continue
                        aligned = self._chunk_matches_intent(text, subq_intent)
                        if not aligned and subq_intent == "methodology":
                            aligned = self._lexical_similarity(sub_q, text) >= 0.03
                        if not aligned:
                            continue
                        sq_score = max(
                            self._lexical_similarity(sub_q, text),
                            float(gc.get("similarity_score", 0.0) or 0.0) * 0.7,
                        )
                        kw_overlap = self._keyword_overlap(sub_q, text)
                        score = (
                            (0.4 * float(gc.get("rrf_score", 0.0) or 0.0))
                            + (0.3 * sq_score)
                            + (0.2 * float(gc.get("evidence_score", 0.0) or 0.0))
                            + (0.1 * kw_overlap)
                        )
                        global_candidates.append({
                            **gc,
                            "subquery_similarity": sq_score,
                            "keyword_overlap": kw_overlap,
                            "final_score": score,
                            "sub_question": sub_q,
                        })
                    global_candidates.sort(key=lambda x: float(x.get("final_score", 0.0) or 0.0), reverse=True)
                    for c in global_candidates:
                        if len(filtered_chunks) >= self.MIN_CHUNKS_PER_SUBQ:
                            break
                        if c not in filtered_chunks:
                            filtered_chunks.append(c)

                # Stage 4: Include abstract-based chunks
                if len(filtered_chunks) < self.MIN_CHUNKS_PER_SUBQ:
                    fallback_stages_used.append("stage4_abstract_chunks")
                    abstract_chunks = [
                        c for c in chunks
                        if str((c.get("metadata") or {}).get("section", c.get("section", ""))).lower() == "abstract"
                    ]
                    abstract_chunks.sort(
                        key=lambda x: float(x.get("rrf_score", x.get("similarity_score", 0.0)) or 0.0),
                        reverse=True,
                    )
                    for c in abstract_chunks:
                        if len(filtered_chunks) >= self.MIN_CHUNKS_PER_SUBQ:
                            break
                        aligned = self._chunk_matches_intent(c.get("text", ""), subq_intent)
                        if not aligned and subq_intent == "methodology":
                            aligned = self._lexical_similarity(sub_q, c.get("text", "")) >= 0.03
                        if not aligned:
                            continue
                        if c not in filtered_chunks:
                            filtered_chunks.append({
                                **c,
                                "subquery_similarity": max(
                                    self._lexical_similarity(sub_q, c.get("text", "")),
                                    float(c.get("similarity_score", 0.0) or 0.0) * 0.7,
                                ),
                                "keyword_overlap": self._keyword_overlap(sub_q, c.get("text", "")),
                                "final_score": float(c.get("rrf_score", c.get("similarity_score", 0.0)) or 0.0),
                                "sub_question": sub_q,
                            })

            # Deduplicate by chunk_id and keep strongest score
            dedup_filtered: Dict[str, Dict[str, Any]] = {}
            for c in filtered_chunks:
                cid = str(c.get("chunk_id", ""))
                if not cid:
                    continue
                if cid not in dedup_filtered or float(c.get("final_score", 0.0) or 0.0) > float(dedup_filtered[cid].get("final_score", 0.0) or 0.0):
                    dedup_filtered[cid] = c
            filtered_chunks = sorted(
                dedup_filtered.values(),
                key=lambda c: float(c.get("final_score", 0.0) or 0.0),
                reverse=True,
            )[: max(self.MAX_CHUNKS_PER_SUBQ, self.MIN_CHUNKS_PER_SUBQ)]

            # Paper coverage guarantee: ensure at least MIN_PAPERS_PER_SUBQ papers.
            paper_ids_now = {
                str(c.get("paper_id", "")) for c in filtered_chunks if str(c.get("paper_id", ""))
            }
            if len(paper_ids_now) < self.MIN_PAPERS_PER_SUBQ:
                fallback_triggered = True
                if "paper_coverage_boost" not in fallback_stages_used:
                    fallback_stages_used.append("paper_coverage_boost")

                paper_candidates = []
                for gc in global_top_chunks:
                    pid = str(gc.get("paper_id", ""))
                    if not pid or pid in paper_ids_now:
                        continue
                    text = gc.get("text", "")
                    aligned = self._chunk_matches_intent(text, subq_intent)
                    if not aligned and subq_intent == "methodology":
                        aligned = self._lexical_similarity(sub_q, text) >= 0.03
                    if not aligned:
                        continue
                    sq_score = max(
                        self._lexical_similarity(sub_q, text),
                        float(gc.get("similarity_score", 0.0) or 0.0) * 0.7,
                    )
                    kw_overlap = self._keyword_overlap(sub_q, text)
                    score = (
                        (0.4 * float(gc.get("rrf_score", 0.0) or 0.0))
                        + (0.3 * sq_score)
                        + (0.2 * float(gc.get("evidence_score", 0.0) or 0.0))
                        + (0.1 * kw_overlap)
                    )
                    paper_candidates.append({
                        **gc,
                        "subquery_similarity": sq_score,
                        "keyword_overlap": kw_overlap,
                        "final_score": score,
                        "sub_question": sub_q,
                    })

                paper_candidates.sort(key=lambda x: float(x.get("final_score", 0.0) or 0.0), reverse=True)
                for c in paper_candidates:
                    if len(paper_ids_now) >= self.MIN_PAPERS_PER_SUBQ:
                        break
                    cid = str(c.get("chunk_id", ""))
                    if not cid:
                        continue
                    if cid not in {str(fc.get("chunk_id", "")) for fc in filtered_chunks}:
                        filtered_chunks.append(c)
                        pid = str(c.get("paper_id", ""))
                        if pid:
                            paper_ids_now.add(pid)

            filtered_chunks = sorted(
                filtered_chunks,
                key=lambda c: float(c.get("final_score", 0.0) or 0.0),
                reverse=True,
            )[: max(self.MAX_CHUNKS_PER_SUBQ + 2, self.MIN_CHUNKS_PER_SUBQ)]

            if filtered_chunks:
                output += f"Intent focus: {subq_intent} | User level: {resolved_user_level}\n\n"

            print(
                f"SubQ: {sub_q} → assigned: {len(assigned_chunks)} → rescored: {len(rescored_chunks)} → after filter: {len(filtered_chunks)} "
                f"→ fallback: {fallback_triggered} → papers: {len({str(c.get('paper_id','')) for c in filtered_chunks if str(c.get('paper_id',''))})}"
            )
            papers_used = len({str(c.get("paper_id", "")) for c in filtered_chunks if str(c.get("paper_id", ""))})
            subq_data["debug"] = {
                "assigned": len(assigned_chunks),
                "rescored": len(rescored_chunks),
                "after_filter": len(filtered_chunks),
                "fallback": fallback_triggered,
                "fallback_used": fallback_triggered,
                "fallback_stages": fallback_stages_used,
                "fallback_triggered": fallback_triggered,
                "num_papers_used": papers_used,
                "intent": subq_intent,
                "user_level": resolved_user_level,
            }
            
            if not filtered_chunks:
                output += "  ⚠ No specific evidence found for this sub-question.\n\n"
                subq_data["mini_summary"] = "No sufficiently relevant evidence was retained for this sub-question."
                analysis_data["sub_questions"].append(subq_data)
                continue

            output += "📌 Evidence Units (Grouped by Paper)\n\n"
            output += "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"

            units: List[Dict[str, Any]] = []
            for chunk in filtered_chunks[:8]:
                subquery_similarity = float(
                    chunk.get(
                        "subquery_similarity",
                        chunk.get("query_similarity", chunk.get("similarity_score", 0.0)),
                    )
                    or 0.0
                )
                unit = self._build_evidence_unit(
                    sub_q,
                    chunk,
                    evidence_extractor,
                    subquery_similarity,
                )
                if unit:
                    units.append(unit)

            if not units:
                output += "⚠ No sufficiently relevant evidence found for this sub-question.\n\n"
                output += "⚠️ Cross-Paper Conflict Analysis\n"
                output += "No conflict analysis available due to missing evidence.\n\n"
                output += "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
                output += "📊 Comparison Summary\n"
                output += "- Supporting evidence clusters: 0\n"
                output += "- Conflicting clusters: 0\n"
                output += "- Consensus level: Low\n\n"
                subq_data["mini_summary"] = "No sufficiently relevant evidence was retained after evidence-unit construction."
                analysis_data["sub_questions"].append(subq_data)
                continue

            # Deduplicate units by chunk-level claim signature
            dedup_map: Dict[str, Dict[str, Any]] = {}
            for u in units:
                key = f"{u.get('paper_id','')}::{u.get('section','')}::{u.get('claim','')[:100]}"
                if key not in dedup_map or u.get("relevance", 0) > dedup_map[key].get("relevance", 0):
                    dedup_map[key] = u
            units = list(dedup_map.values())

            # STEP 6: Consolidate evidence by paper
            merged_evidence = self._merge_paper_evidence(units)
            paper_profiles = self._build_paper_profiles(filtered_chunks)
            
            # STEP 8: Quality gate before output
            quality_check = self._quality_gate(merged_evidence)
            if quality_check["status"] == "rejected":
                output += f"⚠️ Quality Gate REJECTED: {quality_check.get('issues', ['Unknown issue'])}\n\n"
                subq_data["mini_summary"] = f"Evidence rejected by quality gate: {quality_check.get('issues', ['Unknown issue'])}"
                analysis_data["sub_questions"].append(subq_data)
                continue
            
            if quality_check.get("gaps"):
                for gap in quality_check["gaps"]:
                    output += f"⚠️ Coverage Gap: {gap}\n"
                output += "\n"

            grouped: Dict[str, Dict[str, List[Dict[str, Any]]]] = {}
            for unit in units:
                key = f"{unit['paper_title']} ({unit['paper_year']})"
                section_key = unit.get("section", "unknown")
                grouped.setdefault(key, {})
                grouped[key].setdefault(section_key, []).append(unit)

            for paper_key, section_groups in grouped.items():
                output += f"📄 Paper: {paper_key}\n\n"
                idx = 1
                paper_units: List[Dict[str, Any]] = []
                preferred_sections = self._section_preferences(sub_q)
                ordered_sections = sorted(
                    section_groups.items(),
                    key=lambda kv: (
                        1 if kv[0] in preferred_sections else 0,
                        max(
                            (
                                ((u.get("confidence", 0) * 0.6) + (u.get("relevance", 0) * 0.4))
                                * (self.SECTION_PREFERRED_BOOST if kv[0] in preferred_sections else 1.0)
                            )
                            for u in kv[1]
                        ) if kv[1] else 0,
                    ),
                    reverse=True,
                )[: self.MAX_SECTIONS_PER_PAPER]

                for section_name, section_units in ordered_sections:
                    sorted_units = sorted(
                        section_units,
                        key=lambda u: (u.get("final_score", 0), u.get("confidence", 0), u.get("relevance", 0)),
                        reverse=True,
                    )[: self.TOP_CHUNKS_PER_SECTION]

                    for unit in sorted_units:
                        paper_units.append(unit)
                        output += f"[{idx}] Section: {section_name}\n"
                        output += f"Location: sentences {unit['location_start']}–{unit['location_end']}\n"
                        
                        # Add traceability metadata with section correction flag
                        if unit.get("section_corrected"):
                            output += f"[⚠️ Section auto-corrected from: {unit.get('labeled_section', 'unknown')}]\n"
                        if unit.get("nearest_heading"):
                            output += f"[Heading: {unit.get('nearest_heading')}]\n"
                        
                        output += (
                            f"Relevance: {unit['relevance']:.2f} | "
                            f"SubQ Similarity: {unit['subquery_similarity']:.2f} | "
                            f"Confidence: {unit['confidence']:.2f} ({unit['confidence_band']})\n\n"
                        )
                        output += "Text:\n"
                        output += f"\"{unit['text']}\"\n\n"
                        output += "---\n\n"
                        idx += 1

                first_unit = paper_units[0] if paper_units else {}
                subq_data["papers"].append({
                    "paper_id": first_unit.get("paper_id", ""),
                    "paper_title": first_unit.get("paper_title", paper_key),
                    "paper_year": first_unit.get("paper_year", "N/A"),
                    "doi": first_unit.get("paper_doi", ""),
                    "link": first_unit.get("paper_link", ""),
                    "evidence_units": paper_units,
                })
                output += "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            
            # STEP 7: Output structured evidence blocks
            output += "## Evidence by Paper (Merged, Structured)\n\n"
            for paper_id, paper_data in merged_evidence.items():
                output += f"### {paper_data['paper_title']} ({paper_data['paper_year']})\n"
                output += f"**Sections represented:** {', '.join(paper_data.get('sections', []))}\n\n"
                
                if paper_data.get("traceable_citations"):
                    output += f"**Key evidence points:**\n"
                    for i, citation in enumerate(paper_data["traceable_citations"][:3], 1):
                        output += f"\n{i}. **Section:** {citation['section']}\n"
                        if citation.get("heading"):
                            output += f"   **Heading:** {citation['heading']}\n"
                        output += f"   **Location:** {citation['location']}\n"
                        output += f"   **Evidence:** \"{citation['claim'][:150]}...\"\n"
                output += "\n"
            
            # Output traceable citations
            output += "## Traceable Citations\n\n"
            for paper_id, paper_data in merged_evidence.items():
                for citation in paper_data["traceable_citations"]:
                    output += f"[{paper_data['paper_title']} | {citation['section']} | {citation.get('heading', 'N/A')} | {citation['location']}]\n"
                    output += f"\"{citation['text']}\"\n\n"
            
            # Output missing evidence / retrieval gaps if any
            if quality_check.get("gaps"):
                output += "## Missing Evidence / Retrieval Gaps\n\n"
                for gap in quality_check["gaps"]:
                    output += f"- {gap}\n"
                output += "\n"

            conflicts = ConflictDetector.detect_conflicts(units)
            output += "⚠️ Cross-Paper Conflict Analysis\n\n"
            unique_papers = {u.get("paper_id") for u in units if u.get("paper_id")}
            if len(unique_papers) < 2:
                output += "Only one paper available; cross-paper conflict analysis is not applicable.\n\n"
            elif conflicts:
                first = conflicts[0]
                a = first["a"]
                b = first["b"]
                subq_data["conflicts"] = [
                    {
                        "claim_a": (c.get("a", {}).get("claim") or "")[:220],
                        "claim_b": (c.get("b", {}).get("claim") or "")[:220],
                        "type": c.get("type", "Conceptual"),
                        "strength": float(c.get("strength", 0.0) or 0.0),
                        "explanation": c.get("explanation", ""),
                    }
                    for c in conflicts[:3]
                ]
                output += (
                    f"* Claim A ({a['paper_title']} - {a['section']}): \"{(a.get('claim') or '')[:180]}\"\n"
                )
                output += (
                    f"* Claim B ({b['paper_title']} - {b['section']}): \"{(b.get('claim') or '')[:180]}\"\n\n"
                )
                output += f"Conflict Type: {first['type']}\n"
                output += f"Strength: {first['strength']:.2f}\n\n"
                output += f"Explanation: {first.get('explanation','')[:320]}\n\n"
            else:
                output += f"{ConflictDetector.no_conflict_explanation(units)}\n\n"
                subq_data["conflicts"] = []

            comparison_text = self._build_grounded_comparison(sub_q, paper_profiles)

            output += "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            output += "📊 Comparison Summary\n"
            output += f"{comparison_text}\n"
            subq_data["comparison_text"] = comparison_text

            output += "\n🧩 Final Synthesis\n"
            sub_conclusion = self._build_subquestion_conclusion(sub_q, units)
            output += f"{sub_conclusion}\n"
            subq_data["mini_summary"] = sub_conclusion
            analysis_data["sub_questions"].append(subq_data)
            
            output += "\n"
        
        # Summary section
        output += f"{'='*80}\n"
        output += f"SUMMARY\n"
        output += f"{'='*80}\n\n"
        output += f"Total Evidence Sources: {len(chunks)} chunks from {len(set(c.get('paper_id') for c in chunks))} papers\n"
        output += f"Sub-questions Addressed: {len(sub_questions)}\n"
        
        # List all unique papers
        unique_papers = {}
        for chunk in chunks:
            paper_id = chunk.get("paper_id")
            if paper_id not in unique_papers:
                unique_papers[paper_id] = {
                    "title": chunk.get("paper_title"),
                    "year": chunk.get("paper_year")
                }
        
        output += f"\n📚 Papers Referenced:\n"
        for pid, paper in unique_papers.items():
            output += f"   • {paper['title']} ({paper['year']})\n"

        refs: List[Dict[str, Any]] = []
        ref_by_paper: Dict[str, Dict[str, Any]] = {}
        for chunk in chunks:
            pid = chunk.get("paper_id", "")
            if not pid:
                continue
            doi = self._resolve_paper_doi(chunk)
            link = self._resolve_paper_link(chunk)
            if not link and pid:
                # Fallback stable link for traceability when DOI/link missing.
                link = f"https://openalex.org/{pid}" if str(pid).startswith("W") else ""
            ref_by_paper[pid] = {
                "paper_id": pid,
                "title": chunk.get("paper_title", "Unknown"),
                "year": str(chunk.get("paper_year", "N/A")),
                "doi": doi,
                "link": link,
            }
        refs = list(ref_by_paper.values())

        analysis_data["references"] = refs
        analysis_data["stats"] = {
            "chunks_used": len(chunks),
            "papers_used": len(refs),
            "sub_questions": len(sub_questions),
        }

        # ── Phase 3: Build comparison matrix & dataset overlap ────
        comparison_matrix = self._build_comparison_matrix(chunks, refs)
        dataset_overlap = self._build_dataset_overlap(comparison_matrix)
        analysis_data["paper_comparison_matrix"] = comparison_matrix
        analysis_data["cross_paper_dataset_overlap"] = dataset_overlap
        analysis_data["comparison_axes"] = plan.get("comparison_axes", [])
        print(
            f"✓ Comparison matrix: {len(comparison_matrix)} papers, "
            f"{len(dataset_overlap)} shared datasets"
        )

        self._last_analysis = analysis_data
        
        return output
    
    # Minimum chunks each sub-question should receive
    MIN_CHUNKS_PER_SUBQ = 4
    # Minimum paper diversity each sub-question should receive
    MIN_PAPERS_PER_SUBQ = 2
    # A chunk is multi-assigned to another sub-question only if its score
    # is within this fraction of the best score.  0.80 = must be within 20 %.
    MULTI_ASSIGN_RATIO = 0.80
    # Enable multi-assignment only when we have enough unique chunks
    # to avoid repeating the same single chunk under every sub-question.
    MIN_CHUNKS_FOR_MULTI_ASSIGN_FACTOR = 2
    # Max chunks per sub-question to prevent one sub-q from hoarding everything
    MAX_CHUNKS_PER_SUBQ = 5

    def _assign_chunks_to_subquestions(
        self, 
        sub_questions: List[str], 
        chunks: List[Dict[str, Any]],
        adaptive_round: int = 0,
        subquestion_intents: Optional[Dict[str, str]] = None,
    ) -> Dict[str, List[Dict[str, Any]]]:
        """
    Coverage-first assignment with soft penalties and broad utilization.

    Rules:
    - final_score = 0.4*rrf + 0.3*subquery_similarity + 0.2*evidence + 0.1*keyword_overlap
    - low similarity is penalized (not hard-dropped)
    - maintain broad candidate pools per sub-question for fallback stages

        Args:
            sub_questions: List of sub-questions
            chunks: Retrieved chunks

        Returns:
            Dictionary mapping sub-questions to their assigned chunks
        """
        from src.embeddings.embedder import get_shared_embedder

        assignments: Dict[str, List[Dict[str, Any]]] = {sq: [] for sq in sub_questions}
        # Track chunk_ids per sub-question to prevent duplicates
        assigned_ids: Dict[str, set] = {sq: set() for sq in sub_questions}
        resolved_intents = {
            sq: self._infer_intent(sq, (subquestion_intents or {}).get(sq, ""))
            for sq in sub_questions
        }

        if not sub_questions or not chunks:
            return assignments

        # Deduplicate input chunks by chunk_id first
        seen_chunk_ids: set = set()
        unique_chunks: List[Dict[str, Any]] = []
        for c in chunks:
            cid = c.get("chunk_id", id(c))
            if cid not in seen_chunk_ids:
                seen_chunk_ids.add(cid)
                unique_chunks.append(c)
        chunks = unique_chunks

        embedder = get_shared_embedder()

    # ── 1. Build expanded query forms + embeddings ──────────
        subq_forms: Dict[str, List[str]] = {
            sq: self._expand_query_forms(sq)
            for sq in sub_questions
        }
        subq_form_embeddings: Dict[str, List[Any]] = {
            sq: [embedder.embed_text(form) for form in forms]
            for sq, forms in subq_forms.items()
        }

        # Primary embedding kept for compatibility/inspection
        sq_embeddings = [embedder.embed_text(sq) for sq in sub_questions]
        chunk_embeddings = [embedder.embed_text(c.get("text", "")) for c in chunks]

        # score_matrix[i][j] = max similarity(chunk_i, expanded_forms_of_subq_j)
        score_matrix: List[List[float]] = []
        for c_emb in chunk_embeddings:
            row = []
            for j, sq in enumerate(sub_questions):
                _ = sq_embeddings[j]  # retained for explicit compatibility with prior structure
                form_embs = subq_form_embeddings.get(sq, [])
                if not form_embs:
                    row.append(0.0)
                    continue
                max_score = max(float(np.dot(c_emb, f_emb)) for f_emb in form_embs)
                row.append(max_score)
            score_matrix.append(row)

        # ── 2. Chunk mapping: broad per-subquestion candidate pools ──
        min_threshold = 0.60 if adaptive_round == 0 else 0.45
        per_subq_cap = max(self.MAX_CHUNKS_PER_SUBQ * (2 if adaptive_round else 1), self.MIN_CHUNKS_PER_SUBQ)

        for i, chunk in enumerate(chunks):
            if not chunk.get("text"):
                continue
            cid = chunk.get("chunk_id", id(chunk))
            scores = score_matrix[i]
            rrf = float(chunk.get("rrf_score", 0.0) or 0.0)
            evidence_score = float(chunk.get("evidence_score", 0.0) or 0.0)
            text = chunk.get("text", "")

            for j, sq in enumerate(sub_questions):
                sub_sim = float(scores[j])
                kw_overlap = self._keyword_overlap(sq, text)
                intent = resolved_intents.get(sq, "methodology")

                aligned = self._chunk_matches_intent(text, intent)
                if not aligned and intent == "methodology":
                    aligned = self._lexical_similarity(sq, text) >= 0.03
                if not aligned:
                    continue

                penalty = 0.0
                if sub_sim < min_threshold:
                    penalty += (min_threshold - sub_sim) * 0.25

                if self._is_dataset_subquestion(sq):
                    ds_signal = self._dataset_signal_score(text)
                    if ds_signal <= 0:
                        penalty += 0.20
                    else:
                        sub_sim = min(1.0, sub_sim + 0.10 * ds_signal)

                final_score = (
                    (0.4 * rrf)
                    + (0.3 * sub_sim)
                    + (0.2 * evidence_score)
                    + (0.1 * kw_overlap)
                    - penalty
                )

                if len(assignments[sq]) >= per_subq_cap:
                    weakest_idx = min(
                        range(len(assignments[sq])),
                        key=lambda idx: float(assignments[sq][idx].get("final_score", 0.0) or 0.0),
                    )
                    if final_score <= float(assignments[sq][weakest_idx].get("final_score", 0.0) or 0.0):
                        continue
                    old_cid = str(assignments[sq][weakest_idx].get("chunk_id", ""))
                    if old_cid in assigned_ids[sq]:
                        assigned_ids[sq].remove(old_cid)
                    assignments[sq].pop(weakest_idx)

                if cid in assigned_ids[sq]:
                    continue
                assignments[sq].append({
                    **chunk,
                    "primary_subq": sq,
                    "sub_question": sq,
                    "intent": intent,
                    "subquery_similarity": sub_sim,
                    "keyword_overlap": kw_overlap,
                    "penalty": penalty,
                    "final_score": final_score,
                })
                assigned_ids[sq].add(cid)

        for sq in sub_questions:
            assignments[sq].sort(key=lambda x: float(x.get("final_score", 0.0) or 0.0), reverse=True)

        # ── 3. Optional back-fill guarantee ──────────────────────
        if self.MIN_CHUNKS_PER_SUBQ <= 0:
            return assignments

        for j, sq in enumerate(sub_questions):
            if len(assignments[sq]) >= self.MIN_CHUNKS_PER_SUBQ:
                continue

            ranked = sorted(
                range(len(chunks)),
                key=lambda idx: score_matrix[idx][j],
                reverse=True,
            )
            for idx in ranked:
                if len(assignments[sq]) >= self.MIN_CHUNKS_PER_SUBQ:
                    break
                intent = resolved_intents.get(sq, "methodology")
                text = chunks[idx].get("text", "")
                aligned = self._chunk_matches_intent(text, intent)
                if not aligned and intent == "methodology":
                    aligned = self._lexical_similarity(sq, text) >= 0.03
                if not aligned:
                    continue
                cid = chunks[idx].get("chunk_id", id(chunks[idx]))
                if cid not in assigned_ids[sq]:
                    assignments[sq].append({
                        **chunks[idx],
                        "intent": intent,
                        "subquery_similarity": float(score_matrix[idx][j]),
                        "keyword_overlap": self._keyword_overlap(sq, chunks[idx].get("text", "")),
                        "final_score": (
                            (0.4 * float(chunks[idx].get("rrf_score", 0.0) or 0.0))
                            + (0.3 * float(score_matrix[idx][j]))
                            + (0.2 * float(chunks[idx].get("evidence_score", 0.0) or 0.0))
                            + (0.1 * self._keyword_overlap(sq, chunks[idx].get("text", "")))
                            - (0.20 * max(0.0, min_threshold - float(score_matrix[idx][j])))
                        ),
                        "sub_question": sq,
                    })
                    assigned_ids[sq].add(cid)

        return assignments
